### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by josuabarron** [crater-invoice/crater#1074]
**Describe the bug**
When I run setup.sh I get an error, which I can't find a solution for.

**Expected behavior**
Its not running setup.sh

**Please complete the following information:**
- Crater version: latest
- PHP version: 
- Database type and version: mariadb

**Optional info**
- OS:  Synology Docker
- Browser: chrome & Safari

Log:
Fatal error: Uncaught TypeError: json_decode() expects parameter 1 to be string, bool given in phar:///usr/bin/composer/src/Composer/Json/JsonFile.php:194
Stack trace:
#0 phar:///usr/bin/composer/src/Composer/Json/JsonFile.php(194): json_decode(false)
#1 phar:///usr/bin/composer/src/Composer/Factory.php(317): Composer\Json\JsonFile->validateSchema(1)
#2 phar:///usr/bin/composer/src/Composer/Factory.php(625): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), './composer.json', true, '/var/www', true, false)
#3 phar:///usr/bin/composer/src/Composer/Console/Application.php(498): Composer\Factory::create(Object(Composer\IO\ConsoleIO), NULL, true, false)
#4 phar:///usr/bin/composer/src/Composer/Console/Application.php(443): Composer\Console\Application->getComposer(false, true)
#5 phar:///usr/bin/composer/src/Composer/Console/Application.php(388): Composer\Console\Application->hintCommonErrors(Object(ErrorException), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/bin/composer/vendor/symfon in phar:///usr/bin/composer/src/Composer/Json/JsonFile.php on line 194
ERROR: 255

Fatal error: Uncaught TypeError: json_decode() expects parameter 1 to be string, bool given in phar:///usr/bin/composer/src/Composer/Json/JsonFile.php:194
Stack trace:
#0 phar:///usr/bin/composer/src/Composer/Json/JsonFile.php(194): json_decode(false)
#1 phar:///usr/bin/composer/src/Composer/Factory.php(317): Composer\Json\JsonFile->validateSchema(1)
#2 phar:///usr/bin/composer/src/Composer/Factory.php(625): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), './composer.json', true, '/var/www', true, false)
#3 phar:///usr/bin/composer/src/Composer/Console/Application.php(498): Composer\Factory::create(Object(Composer\IO\ConsoleIO), NULL, true, false)
#4 phar:///usr/bin/composer/src/Composer/Console/Application.php(443): Composer\Console\Application->getComposer(false, true)
#5 phar:///usr/bin/composer/src/Composer/Console/Application.php(388): Composer\Console\Application->hintCommonErrors(Object(ErrorException), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/bin/composer/vendor/symfon in phar:///usr/bin/composer/src/Composer/Json/JsonFile.php on line 194
ERROR: 255
Could not open input file: artisan
ERROR: 1
Could not open input file: artisan
ERROR: 1

**Comment by f0f0-cr** [comment]
Hi,

This is because you are running the "setup.sh" from the "docker-compose" folder, please run this from the "root" folder where you have the code.

Step 5, docker installation, -> https://docs.craterapp.com/installation.html#docker-installation
